config/routes.rb
Rails.application.routes.draw do

  resources :grants
  get 'search' => 'application#search'
  root 'application#home'

end

app/models/grant.rb
class Grant < ActiveRecord::Base

  def self.uniq_rows(column_name)
    Grant.select(column_name).uniq.map(&column_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
  end

  def search
  end

end

app/controllers/grants_controller.rb
class GrantsController < ApplicationController
  def index
    grant = Grant.where(grant_params).first
    if grant_params.nil? or grant.nil?
      flash[:error] = 'Error occurred. Please try again.'
      redirect_to search_path
    else
      @grants = grant.results.split('/')
    end
  end

  def grant_params
    params.require(:grant).permit(:reg_sg,:staff,:age,:shareholding,:turnover,:industry,:challenge,:pain_point)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grants_helper.rb
module GrantsHelper
end

app/views/application/home.html.erb
<div class='container' style="text-align:center;">
  <%= image_tag "/SPRING-logo-colour.jpg", style:'width:100%;'%>
  <br>
  <br>
  <%= link_to 'Start', search_path , class: 'btn btn-success'%>
</div>

app/views/application/search.html.erb
<div class="container">
  <% if flash[:error].present? %>
    <br>
    <div class="alert alert-danger">
      <%= flash[:error] %>
    </div>
  <% end %>
<h1>Search</h1>
<%= form_tag grants_path, method: :get, class: 'inline-form' %>
  <span>My company is </span>
  <%= select_tag "grant[reg_sg]", options_for_select(Grant.uniq_rows(:reg_sg)),prompt: '',class: 'form-control inline-input'  %>
  <span>. There are </span>
  <%= select_tag "grant[staff]", options_for_select(Grant.uniq_rows(:staff)),prompt: '',class: 'form-control inline-input'  %>
  <span> employees and we have been operating for </span>
  <%= select_tag "grant[age]", options_for_select(Grant.uniq_rows(:age)),prompt: '',class: 'form-control inline-input'  %>
  <span>. </span>
  <%= select_tag "grant[shareholding]", options_for_select(Grant.uniq_rows(:shareholding)),prompt: '',class: 'form-control inline-input'  %>
  <span> of my company's share is owned by Singapore Citizens or Permanent Residents. Our annual turnover is </span>
  <%= select_tag "grant[turnover]", options_for_select(Grant.uniq_rows(:turnover)),prompt: '',class: 'form-control inline-input'  %>
  <span>. We work in the </span>
  <%= select_tag "grant[industry]", options_for_select(Grant.uniq_rows(:industry)),prompt: '',class: 'form-control inline-input'  %>
  <span> industry and our greatest business challenge is in </span>
  <%= select_tag "grant[challenge]", options_for_select(Grant.uniq_rows(:challenge)),prompt: '',class: 'form-control inline-input'  %>
  <span>, specifically in the area of </span>
  <%= select_tag "grant[pain_point]", options_for_select(Grant.uniq_rows(:pain_point)),prompt: '',class: 'form-control inline-input'  %>
  <span>.</span>
  <br>
  <%= submit_tag "Submit", class:'btn btn-success'%>
</div>

app/views/grants/index.html.erb
<div class="container">
  <h1> Your search returned <%= @grants.count%> results</h1>
  <ul>
  <% @grants.each do |grant| %>
    <li>
    <%= grant %>
    </li>
  <% end %>
  </ul>
  <%= link_to "Home", "/", class: 'btn btn-info' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GrantApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="default" />
  <link rel="apple-touch-icon" href="favicon-64.jpg"/> 
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>